Repository Vladmar11/Twilight-Fortress, pull requests merged in 2025-01, with the labels that each got.

#31 Швея переводится
  .gitignore
  code/datums/loadout.dm
  code/game/objects/items/rogueitems/bags.dm
  code/game/objects/items/rogueitems/leash.dm
  code/game/objects/items/rogueitems/natural/clothfibersthorn.dm
  code/game/objects/structures/beds_chairs/roguechair.dm
  code/modules/cargo/packsrogue/stuff.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/gloves.dm
  code/modules/clothing/rogueclothes/hats/hats.dm
  code/modules/clothing/rogueclothes/leather/armor.dm
  code/modules/clothing/rogueclothes/leather/gloves.dm
  code/modules/clothing/rogueclothes/leather/pants.dm
  code/modules/clothing/rogueclothes/leather/shoes.dm
  code/modules/clothing/rogueclothes/mask.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/new/cloaks.dm
  code/modules/clothing/rogueclothes/new/gloves.dm
  code/modules/clothing/rogueclothes/new/masks.dm
  code/modules/clothing/rogueclothes/new/pants.dm
  code/modules/clothing/rogueclothes/new/shirts.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/clothing/rogueclothes/robes.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/clothing/rogueclothes/shoes.dm
  code/modules/clothing/rogueclothes/wrists.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  modular/code/game/objects/items/clothes/stockings.dm
  modular/code/game/objects/items/clothes/strapless_dress.dm
Labels: Тест-мердж

#36 Based Heartfelt
  code/datums/gods/faiths/zizo.dm
  code/datums/gods/patrons/psydon.dm
  code/datums/migrants/migrant_waves/heartfelt roles.dm
  code/datums/migrants/migrant_waves/heartfelt wave.dm
  strings/rt/rp_prompt.txt
Labels: Тест-мердж

#40 doctors buff
  code/modules/jobs/job_types/roguetown/bandits/types/sawbones.dm
  code/modules/jobs/job_types/roguetown/nobility/physician.dm
  code/modules/jobs/job_types/roguetown/refugees/types/healer.dm
  code/modules/jobs/job_types/roguetown/towners/types/towndoctor.dm
  code/modules/spells/roguetown/acolyte/sawbones.dm
Labels: Тест-мердж

#42 Duke and Consort, Priest adj, Addiction reflawed
  code/datums/character_flaw/addiction.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/mercenaries/types/grenzelhoft.dm
  code/modules/jobs/job_types/roguetown/mercenaries/types/grenzelhoft_kommandant.dm
  code/modules/jobs/job_types/roguetown/nobility/consort.dm
  code/modules/jobs/job_types/roguetown/nobility/ruler.dm
Labels: Тест-мердж

#39 Драконодевочки уже без страшного
  code/__DEFINES/roguetown.dm
  code/modules/client/customizer/customizer.dm
  code/modules/client/customizer/customizers/organ/horns.dm
  code/modules/client/customizer/customizers/organ/tail.dm
  code/modules/mob/dead/new_player/body_markings/body_marking_dragongirl.dm
  code/modules/mob/dead/new_player/body_markings/body_marking_sets.dm
  code/modules/mob/dead/new_player/sprite_accessory/horns.dm
  code/modules/mob/dead/new_player/sprite_accessory/tails.dm
  code/modules/mob/living/carbon/human/species_types/furry/dragongirls.dm
  code/modules/surgery/bodyparts/bodypart_examine.dm
  code/modules/surgery/organs/feature_organs/tails.dm
  icons/mob/body_markings/dragongirls_markings.dmi
  icons/mob/sprite_accessory/horns/dragongirl.dmi
  icons/mob/sprite_accessory/tails/dragongirl.dmi
  roguetown.dme
Labels: Тест-мердж

#86 Knob8
  code/__DEFINES/misc.dm
  code/controllers/subsystem/nightshift.dm
  code/datums/components/darkling.dm
  code/datums/elements/tipped_item.dm
  code/datums/pollution.dm
  code/datums/status_effects/rogue/debuff.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/game/objects/items.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/turfs/open/water.dm
  code/modules/cargo/packsrogue/apparel.dm
  code/modules/cargo/packsrogue/armor.dm
  code/modules/cargo/packsrogue/food.dm
  code/modules/cargo/packsrogue/luxury.dm
  code/modules/cargo/packsrogue/seeds.dm
  code/modules/cargo/packsrogue/tools.dm
  code/modules/cargo/packsrogue/wardrobe.dm
  code/modules/cargo/packsrogue/weapons.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/hats/hats.dm
  code/modules/clothing/rogueclothes/leather/armor.dm
  code/modules/clothing/rogueclothes/robes.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/clothing/rogueclothes/temp/citywatch.dm
  code/modules/clothing/rogueclothes/temp/councillor.dm
  code/modules/clothing/rogueclothes/temp/duchess.dm
  code/modules/clothing/rogueclothes/temp/duke.dm
  code/modules/clothing/rogueclothes/temp/hand.dm
  code/modules/clothing/rogueclothes/temp/heir.dm
  code/modules/clothing/rogueclothes/temp/heiress.dm
  code/modules/clothing/rogueclothes/temp/magos.dm
  code/modules/clothing/rogueclothes/temp/steward.dm
  code/modules/jobs/job_types/roguetown/yeomen/merchant.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/roguetown/roguejobs/miner/rogueores.dm
  code/modules/roguetown/roguemachine/merchant.dm
  code/modules/roguetown/roguestock/stockpile.dm
  code/modules/spells/roguetown/acolyte/sawbones.dm
  icons/roguetown/clothing/onmob/helpers/sleeves_shirts.dmi
  icons/roguetown/clothing/onmob/shirts.dmi
  roguetown.dme
Labels: Balance, Spriting

#90 Knob8
  code/controllers/subsystem/ai_controller.dm
  code/datums/ai/_ai_behaviour.dm
  code/datums/ai/_ai_controller.dm
  code/datums/migrants/migrant_wave.dm
  code/game/gamemodes/roguetown/roguetown.dm
  code/modules/jobs/job_types/roguetown/towners/types/blacksmith.dm
  code/modules/jobs/job_types/roguetown/yeomen/blacksmith.dm
  code/modules/roguetown/roguecrafting/structure.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/_anvil_recipe.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/cutlery.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/valuables.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
Labels: Balance
