Repository Vladmar11/Twilight-Fortress, pull requests merged in 2025-02, with the labels that each got.

#95 Банворды Ксиликса и не только
  code/modules/clothing/rogueclothes/leather/armor.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/modules/spells/roguetown/acolyte/xylix.dm
Labels: Balance

#93 add girl kissing
  code/__HELPERS/mobs.dm
  code/datums/mob_descriptors/descriptors/other.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/job_types/roguetown/nobility/consort.dm
  code/modules/mob/living/living_descriptors.dm
Labels: Balance

#98 Courtiers joinlate window fix
  code/modules/jobs/job_types/roguetown/courtier/butler.dm
  code/modules/jobs/jobs.dm
Labels: Balance

#102 Knob99
  code/datums/keybinding/living.dm
  code/modules/jobs/job_types/roguetown/courtier/councillor.dm
  code/modules/jobs/job_types/roguetown/towners/types/miner.dm
  code/modules/mob/dead/new_player/sprite_accessory/tails.dm
  code/modules/mob/living/carbon/human/species_types/furry/kobold.dm
  code/modules/mob/living/carbon/human/species_types/furry/lizardfolk.dm
  code/modules/mob/living/living.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/modules/roguetown/roguejobs/artificer/handsaw_chisel.dm
  code/modules/roguetown/roguejobs/tailor/dyer.dm
  icons/mob/sprite_accessory/tails/tails.dmi
Labels: Balance, Spriting

#105 perenos
  code/__DEFINES/colors.dm
  code/modules/jobs/job_types/roguetown/towners/types/blacksmith.dm
  code/modules/roguetown/roguejobs/tailor/dyer.dm
Labels: Balance

#109 Knob103
  code/datums/components/footstep.dm
  code/datums/migrants/migrant_waves/slaver roles.dm
  code/modules/cargo/packsrogue/wardrobe.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/clothing/rogueclothes/shoes.dm
  code/modules/clothing/rogueclothes/storage.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/valuables.dm
  icons/roguetown/clothing/belts.dmi
  icons/roguetown/clothing/feet.dmi
  icons/roguetown/clothing/masks.dmi
  icons/roguetown/clothing/onmob/belts.dmi
  icons/roguetown/clothing/onmob/feet.dmi
  icons/roguetown/clothing/onmob/masks.dmi
  icons/roguetown/clothing/onmob/shirts.dmi
  icons/roguetown/clothing/shirts.dmi
Labels: Balance, Spriting

#111 Perenosi
  code/__DEFINES/magic/spells.dm
  code/datums/special_traits/traits/traits.dm
  code/game/objects/items/rogueitems/devices.dm
  code/game/objects/structures/roguetown/rogueflora.dm
  code/modules/antagonists/roguetown/villain/werewolf/werewolf_transformation.dm
  code/modules/jobs/job_types/roguetown/bandits/types/hedgeknight.dm
  code/modules/jobs/job_types/roguetown/bandits/types/roguemage.dm
  code/modules/jobs/job_types/roguetown/bandits/types/sawbones.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/courtier/jester.dm
  code/modules/jobs/job_types/roguetown/garrison/bogmaster.dm
  code/modules/jobs/job_types/roguetown/garrison/sheriff.dm
  code/modules/jobs/job_types/roguetown/goblin/goblinshaman.dm
  code/modules/jobs/job_types/roguetown/mercenaries/seelie.dm
  code/modules/jobs/job_types/roguetown/mercenaries/types/newmoon.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/nobility/consort.dm
  code/modules/jobs/job_types/roguetown/nobility/hand.dm
  code/modules/jobs/job_types/roguetown/nobility/magician.dm
  code/modules/jobs/job_types/roguetown/nobility/marshal.dm
  code/modules/jobs/job_types/roguetown/nobility/physician.dm
  code/modules/jobs/job_types/roguetown/nobility/ruler.dm
  code/modules/jobs/job_types/roguetown/other/deathknight.dm
  code/modules/jobs/job_types/roguetown/peasants/nightman.dm
  code/modules/jobs/job_types/roguetown/refugees/types/healer.dm
  code/modules/jobs/job_types/roguetown/refugees/types/magos.dm
  code/modules/jobs/job_types/roguetown/towners/types/towndoctor.dm
  code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
  code/modules/jobs/job_types/roguetown/yeomen/seamster.dm
  code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
  code/modules/jobs/job_types/roguetown/youngfolk/servant.dm
  code/modules/mob/living/living.dm
  code/modules/spells/roguetown/wizard.dm
  roguetown.dme
Labels: Balance

#116 perenosi
  code/modules/paperwork/rogue.dm
Labels: Spriting

#118 [SPRITE FIX] Тело, уши гоблинов + глаза всех низких рас
  code/modules/mob/living/carbon/human/species_types/furry/anthromorphsmall.dm
  code/modules/mob/living/carbon/human/species_types/furry/kobold.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/goblin/goblinp.dm
  icons/mob/species/goblin_female.dmi
  icons/mob/species/goblin_male.dmi
  icons/mob/sprite_accessory/ears/ears.dmi
Labels: Spriting

#120 Perenosi
  code/datums/character_flaw/_character_flaw.dm
  code/game/objects/items/rogueweapons/melee/blunt.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  icons/roguetown/weapons/daggerherald.dmi
  icons/roguetown/weapons/idaggerherald.dmi
  icons/roguetown/weapons/iswordherald.dmi
  icons/roguetown/weapons/maceherald.dmi
  icons/roguetown/weapons/smaceherald.dmi
  icons/roguetown/weapons/swordherald.dmi
Labels: Spriting

#121 [SPRITING & CODE] Шестерёнки, спрайты и фиксы
  code/modules/clothing/rogueclothes/wrists.dm
  code/modules/roguetown/roguejobs/artificer/artificer recipes/artificer_recipes.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  code/modules/roguetown/roguejobs/engineering/items.dm
  icons/roguetown/items/misc.dmi
  modular_twilight/code/modules/roguetown/roguejobs/engineering/items.dm
  modular_twilight/icons/roguetown/items/misc.dmi
  roguetown.dme
Labels: Spriting

#123 Perenosi
  code/game/objects/items/rogueitems/natural/clothfibersthorn.dm
Labels: Spriting
